# Generated by Django 2.1.1 on 2018-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('line', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
